### ISSUE TITLE
Help with attribute

### ISSUE THREAD

**Issue by bryankerr1986** [VUnit/vunit#987]
Hello,

I have declared an attribute to mark my testbench.

Also, in my run.py script I have a piece of code that generates vivado output products before code is compiled.

If I try to only run certain testbenches with the attribute, the problem is every run.py script will still generate vivado output products - wasting time.

Is there a way you can think of to skip this? It seems the attribute doesn't take affect until everything is compiled.

Does VUnit provide some other solution for this?

For context, I'm using VUnit with Xcelium, so maybe everything is not supported.

Thanks!
Bryan

**Comment by LarsAsplund** [comment]
What you could do is to add a custom command line option with which you decide if the Vivado output should be generated or not. See https://vunit.github.io/py/ui.html#adding-custom-command-line-arguments.

Rather than adding a new option, you can use the same approach to peek the values of the standard options. Maybe you can simply look at if the run is made with the attribute filter options and then skip the Vivado outputs
